# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details

#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11
        environment:
          TZ: "Europe/Amsterdam"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/prodream-embedded

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: prodream-embedded-{{ checksum "pom.xml" }}

      - run: mvn package dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: prodream-embedded-{{ checksum "pom.xml" }}

      # run tests! and gen code coverage
      - run: mvn integration-test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/site/jacoco/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

#      - run:
#          name: Send to CodeCov
#          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
